name=input("enter name: ")
branch=input("enter branch: ")
gender=input("enter gender: ")
college=input("enter college: ")
age=input("enter age: ")
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("college:",college)
print("age:",age)
